x = input('Digite algo: ')
print('O tipo primitivo é: ', type(x))
print('Só tem espaços? ', x.isspace())
print('É um número? ', x.isnumeric())
print('É alfabetico?', x.isalpha())
print('É alfanumerico? ', x.isalnum())
print('Esta em maisculo? ', x.isupper())
print('Esta em minusculo? ', x.islower())
print('Está captalizada? ', x.istitle())